apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeJanitor.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubeJanitor.labels" . | nindent 4 }}
