{{- if eq .Values.kind "CronJob" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "kubeJanitor.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubeJanitor.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cron.schedule }}"
  {{- if .Values.cron.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.cron.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if .Values.cron.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cron.failedJobsHistoryLimit }}
  {{- end }}
  {{- if .Values.cron.suspend }}
  suspend: {{ .Values.cron.suspend }}
  {{- end }}
  {{- if .Values.cron.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.cron.startingDeadlineSeconds }}
  {{- end }}
  jobTemplate:
    metadata:
      labels:
        {{- include "kubeJanitor.selectorLabels" . | nindent 8 }}
    spec:
      template:
        metadata:
          labels:
            {{- include "kubeJanitor.selectorLabels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ template "kubeJanitor.fullname" . }}
          restartPolicy: {{ .Values.cron.restartPolicy }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{ toYaml . | indent 12 }}
          {{- end }}
          {{- with .Values.image.pullSecrets }}
          imagePullSecrets:
            {{ toYaml . | indent 12 }}
          {{- end }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
              {{- include "kubeJanitor.args" . | indent 14 }}
            {{- with .Values.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            securityContext:
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
            {{- if .Values.kubejanitor.rules }}
            volumeMounts:
              - name: {{ template "kubeJanitor.fullname" . }}-volume
                mountPath: /config
            {{- end }}
          {{- if .Values.kubejanitor.rules }}
          volumes:
            - name: {{ template "kubeJanitor.fullname" . }}-volume
              configMap:
                name: {{ template "kubeJanitor.fullname" . }}
          {{- end }}
{{- end }}
